### ISSUE TITLE
Python runtime state: core initialized ModuleNotFoundError: No module named 'encodings'

### ISSUE THREAD

**Issue by huanggou666** [daswer123/hallo-webui#12]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'C:\ALLWEBUI\hallo\hallo-portable-2\system\python\python.exe'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\ALLWEBUI\\hallo\\hallo-portable-2\\system\\python\\python.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\ALLWEBUI\\hallo\\hallo-portable-2\\webui\\venv\\Scripts\\python.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\ALLWEBUI\\hallo\\hallo-portable-2\\system\\python\\python310.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\ALLWEBUI\\hallo\\hallo-portable-2\\system\\python',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00005110 (most recent call first):
  <no Python frame>
请按任意键继续. . .

**Comment by joeluo** [comment]
我用 portable 也是這種結果，後來改用 manual ，也很好安裝，可以參考我的影片。
I also had the same result when using portable. Later I switched to manual, which was also easy to install. You can refer to my video.
https://youtu.be/JX9EP7o4KCg

**Comment by huanggou666** [comment]
> 我用 portable 也是這種結果，後來改用 manual ，也很好安裝，可以參考我的影片。 I also had the same result when using portable. Later I switched to manual, which was also easy to install. You can refer to my video. https://youtu.be/JX9EP7o4KCg

谢谢，原来是python版本的问题，电脑上安装一个3.10.11版本 然后这样创建虚拟环境就可以了， `"C:\Users\admin\AppData\Local\Programs\Python\Python310\python.exe" -m venv myhallo
myhallo\Scripts\activate

`

**Comment by huanggou666** [comment]
Got it running but when I hit generate , I got this Error :
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ALLWEBUI\hallocmd\hallo-webui\myhallo\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "C:\ALLWEBUI\hallocmd\hallo-webui\app.py", line 60, in generate_video
    result = subprocess.run(command, check=True)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by joeluo** [comment]
May be the file name too long, please make the hallo's folder under the root directory.

**Comment by leven-ls** [comment]
change the app.py line 24, to your real python executable.
![1726322350878](https://github.com/user-attachments/assets/4062b0a8-1b9c-4a10-9039-f7222b145fc1)
