### ISSUE TITLE
ERROR when starting the process using the portable "Triton is not available"

### ISSUE THREAD

**Issue by TomiTom1234** [daswer123/hallo-webui#16]
I get this error after I generate the video using the portable file:

```
E:\AI\hallo-portable-2\webui\venv\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "E:\AI\hallo-portable-2\webui\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "E:\AI\hallo-portable-2\webui\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
Traceback (most recent call last):
  File "E:\AI\hallo-portable-2\webui\scripts\inference.py", line 40, in <module>
    from hallo.animate.face_animate import FaceAnimatePipeline
ModuleNotFoundError: No module named 'hallo'
```

Any idea how to solve this please?

**Comment by TomiTom1234** [comment]
EDIT:

OK I found the solution.
I just moved the "hallo" directory to "scripts" directory, then the error stopped.
And now it is generating.

**Comment by dreamhacking** [comment]
you are awesome, it worked

**Comment by TomiTom1234** [comment]
> you are awesome, it worked

Glad it worked for you
