### ISSUE TITLE
'tuple' object has no attribute 'shape'

### ISSUE THREAD

**Issue by O-O1024** [daswer123/hallo-webui#20]
```
Traceback (most recent call last):
  File "/root/hallo-webui/scripts/inference.py", line 424, in <module>
    inference_process(
  File "/root/hallo-webui/scripts/inference.py", line 300, in inference_process
    audio_emb = process_audio_emb(audio_emb)
  File "/root/hallo-webui/scripts/inference.py", line 109, in process_audio_emb
    for i in range(audio_emb.shape[0]):
AttributeError: 'tuple' object has no attribute 'shape'
```

**Comment by marco-cinalli** [comment]
I have identical error. I am running this on Ubuntu (with LighningAi) . I could not find a solution yet.
