### ISSUE TITLE
multiple errors "matching Triton is not available" "No module named 'triton'" "No module named 'hallo'"

### ISSUE THREAD

**Issue by ikitikat** [daswer123/hallo-webui#5]
I used the portable windows version and run the update.bat. Everything is up to date. Then while running run.bat the web interface will be shown. When i then try to generate a video i get the following errors in the console:

> hallo-portable-2\webui\venv\lib\site-packages\transformers\utils\hub.py:124: FutureWarning: Using TRANSFORMERS_CACHE is deprecated and will be removed in v5 of Transformers. Use HF_HOME instead.
>   warnings.warn(
> A matching Triton is not available, some optimizations will not be enabled
> Traceback (most recent call last):
>   File "hallo-portable-2\webui\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
>     from xformers.triton.softmax import softmax as triton_softmax  # noqa
>   File "hallo-portable-2\webui\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
>     import triton
> ModuleNotFoundError: No module named 'triton'
> Traceback (most recent call last):
>   File "hallo-portable-2\webui\scripts\inference.py", line 40, in <module>
>     from hallo.animate.face_animate import FaceAnimatePipeline
> ModuleNotFoundError: No module named 'hallo'

In the web interface the following error is shown:

> Error: Command '['venv\\Scripts\\python.exe', 'scripts\\inference.py', '--source_image', 'hallo-portable-2\\tmp\\gradio\\7642a58eaec640f24fa498286998572f933e2566\\image_512.jpeg', '--driving_audio', 'hallo-portable-2\\tmp\\gradio\\36b61bbbf03ba5a4c9eb63d08e12d390b690361a\\audio.wav', '--output', 'output/20240620-011042.mp4', '--face_expand_ratio', '1.2', '--setting_steps', '40', '--setting_cfg', '3.5', '--settings_seed', '42', '--settings_fps', '25', '--settings_motion_pose_scale', '1', '--settings_motion_face_scale', '1', '--settings_motion_lip_scale', '1', '--settings_n_motion_frames', '2', '--settings_n_sample_frames', '16']' returned non-zero exit status 1.

Running on Windows 10 and Nvidia GeForce RTX 4090 with 24 GB VRAM and 64 GB RAM

**Comment by djzigoh** [comment]
same here

**Comment by RaiderUser** [comment]
I only get the info message, but would be better if it works, I guess. 
```
A matching Triton is not available, some optimizations will not be enabled
```

**Comment by NergiZed** [comment]
Edit: Problem solved. I just needed to make the input image a perfect square or it won't work. Prep your input data!

Yeah, same here. I get the following:

`A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\AI\Hallo\hallo-webui-main\venv\lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
  File "C:\AI\Hallo\hallo-webui-main\venv\lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
WARNING:py.warnings:C:\AI\Hallo\hallo-webui-main\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(`

I can't code, so I'm not sure what's going on. I'll poke around and see if I can find out what this module is and where to install it.

Running the install.bat again does not solve the problem, I don't think this module appears in install.bat

Edit:
I also get this error in the UI:
`

Audio

0:42
0:42
1x








Settings
▼
Face Expand Ratio
1.2

Steps
40

CFG Scale
3.5

Seed
42
FPS
25


Motion Scale
▼
Motion Pose Scale
1

Motion Face Scale
1

Motion Lip Scale
1


Extra Settings
▼
N Motion Frames
2

N Sample Frames
16

Label
Error: Command '['venv\\Scripts\\python.exe', 'scripts\\inference.py', '--source_image', 'C:\\Users\\PC\\AppData\\Local\\Temp\\gradio\\5f00786ad9ab7c8b759b11d6e90980d7999d9371\\Dongho_Kang_image045.png', '--driving_audio', 'C:\\Users\\PC\\AppData\\Local\\Temp\\gradio\\165475befdfd20237fdeea94cb883aded9d1dcfa\\Positive Affirmation Clip 1.wav', '--output', 'output/20240621-094909.mp4', '--face_expand_ratio', '1.2', '--setting_steps', '40', '--setting_cfg', '3.5', '--settings_seed', '42', '--settings_fps', '25', '--settings_motion_pose_scale', '1', '--settings_motion_face_scale', '1', '--settings_motion_lip_scale', '1', '--settings_n_motion_frames', '2', '--settings_n_sample_frames', `

Edit 2:

Might as well post the entire log. 

![image](https://github.com/daswer123/hallo-webui/assets/60335527/40f3c67d-0b1f-4ace-b6de-49294640f567)

**Comment by assassinliujie** [comment]
"I found during testing that manually importing 'hallo' in the root directory works successfully, but importing it in the 'scripts' directory does not. Therefore, I moved 'inference.py' to the root directory and modified app.py, And it works for me

**Comment by assassinliujie** [comment]
command = [
            "python3",
            "inference.py",
            "--source_image", ref_img,
            "--driving_audio", ref_audio,
            "--output", output_video,
            "--setting_steps", str(setting_steps),
            "--setting_cfg", str(setting_cfg),
            "--settings_seed", str(settings_seed),
            "--settings_fps", str(settings_fps),
            "--settings_motion_pose_scale", str(settings_motion_pose_scale),
            "--settings_motion_face_scale", str(settings_motion_face_scale),
            "--settings_motion_lip_scale", str(settings_motion_lip_scale),
            "--settings_n_motion_frames", str(settings_n_motion_frames),
            "--settings_n_sample_frames", str(settings_n_sample_frames)

**Comment by assassinliujie** [comment]
just change the scripts/inference.py to inference.py, and copy inference.py to the root directory
